Repository dialob/dialob-parent, pull requests merged in 2025-01, with the labels that each got.

#270 Do not filter out groups when there is no tenant bound to it
  dialob-config-parent/dialob-settings/src/main/java/io/dialob/settings/DialobSettings.java
  dialob-config-parent/dialob-settings/src/main/resources/application-oauth2.yml
  dialob-config-parent/dialob-settings/src/main/resources/application-openid.yml
  dialob-security-parent/dialob-security-aws/src/test/java/io/dialob/security/aws/DialobSecurityAwsAutoConfigurationTest.java
  dialob-security-parent/dialob-security-spring/src/main/java/io/dialob/security/spring/DialobSecuritySpringAutoConfiguration.java
  dialob-security-parent/dialob-security-spring/src/main/java/io/dialob/security/spring/oauth2/MapClaimToGroups.java
  dialob-security-parent/dialob-security-spring/src/test/java/io/dialob/security/spring/DialobSecuritySpringAutoConfigurationTest.java
  dialob-security-parent/dialob-security-spring/src/test/java/io/dialob/security/spring/oauth2/StreamingGrantedAuthoritiesMapperTest.java
  dialob-security-parent/dialob-security-spring/src/test/resources/logback-test.xml
Labels: bug

#263 Added a rest service which handles csv format form post requests
  dialob-components/dialob-form-service-api/src/main/java/io/dialob/form/service/api/validation/CsvToFormParser.java
  dialob-components/dialob-form-service-rest/src/main/java/io/dialob/form/service/rest/FormsRestService.java
  dialob-components/dialob-form-service-rest/src/main/java/io/dialob/form/service/rest/FormsRestServiceController.java
  dialob-components/dialob-form-service-rest/src/test/java/io/dialob/form/service/rest/FormsRestServiceControllerTest.java
  dialob-components/dialob-form-service/pom.xml
  dialob-components/dialob-form-service/src/main/java/io/dialob/form/service/CsvParsingException.java
  dialob-components/dialob-form-service/src/main/java/io/dialob/form/service/DialobCsvToFormParser.java
  dialob-components/dialob-form-service/src/main/java/io/dialob/form/service/DialobFormServiceAutoConfiguration.java
  frontend/dialob-material-dashboard/src/DialobAdminView.tsx
  frontend/dialob-material-dashboard/src/backend/index.ts
  frontend/dialob-material-dashboard/src/intl/index.ts
Labels: development, backend

#297 Remove obsolete Dialob API database integration.
  README.md
  dialob-bom/pom.xml
  dialob-components/dialob-db-dialob-api/pom.xml
  dialob-components/dialob-db-dialob-api/src/main/java/io/dialob/db/dialob/api/AbstractDialobApiDatabase.java
  dialob-components/dialob-db-dialob-api/src/main/java/io/dialob/db/dialob/api/DialobApiDbSettings.java
  dialob-components/dialob-db-dialob-api/src/main/java/io/dialob/db/dialob/api/DialobApiFormDatabase.java
  dialob-components/dialob-db-dialob-api/src/main/java/io/dialob/db/dialob/api/DialobApiQuestionnaireDatabase.java
  dialob-components/dialob-db-dialob-api/src/main/java/io/dialob/db/dialob/api/DialobApiTemplate.java
  dialob-components/dialob-db-sp-spring/pom.xml
  dialob-components/dialob-db-sp-spring/src/main/java/io/dialob/db/sp/DialobDbSpAutoConfiguration.java
  dialob-components/pom.xml
  dialob-config-parent/dialob-settings/src/main/java/io/dialob/settings/DialobSettings.java
  dialob-config-parent/dialob-settings/src/main/resources/application-dialobapidb.yml
  dialob-session-boot/pom.xml
Labels: backend

#299 Remove Groovy functions support from the project
  README.md
  dialob-bom/pom.xml
  dialob-boot/pom.xml
  dialob-build-parent/pom.xml
  dialob-components/dialob-groovy-functions/pom.xml
  dialob-components/dialob-groovy-functions/src/main/java/io/dialob/groovy/DialobDDRLFunction.java
  dialob-components/dialob-groovy-functions/src/main/java/io/dialob/groovy/DialobGroovyFunctionsAutoConfiguration.java
  dialob-components/dialob-groovy-functions/src/main/java/io/dialob/groovy/GroovyFunctionRegistry.java
  dialob-components/dialob-groovy-functions/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  dialob-components/dialob-groovy-functions/src/test/java/io/dialob/groovy/GroovyFunctionRegistryTest.java
  dialob-components/dialob-groovy-functions/src/test/resources/logback-test.xml
  dialob-components/dialob-groovy-functions/src/test/resources/scripts/mapping.groovy
  dialob-components/dialob-groovy-functions/src/test/resources/scripts/test.groovy
  dialob-components/pom.xml
  dialob-session-boot/pom.xml
  docs/dialob-groovy-functions.md
Labels: backend

#305 Resolve reliability issues found by sonarqube (#304)
  dialob-api/src/main/java/io/dialob/api/form/Form.java
  dialob-api/src/main/java/io/dialob/api/form/FormItem.java
  dialob-api/src/main/java/io/dialob/api/form/FormTag.java
  dialob-api/src/main/java/io/dialob/api/form/FormValueSet.java
  dialob-api/src/main/java/io/dialob/api/form/FormValueSetEntry.java
  dialob-api/src/main/java/io/dialob/api/form/Validation.java
  dialob-api/src/main/java/io/dialob/api/form/Variable.java
  dialob-api/src/main/java/io/dialob/api/questionnaire/ContextValue.java
  dialob-api/src/main/java/io/dialob/api/questionnaire/Questionnaire.java
  dialob-api/src/main/java/io/dialob/api/questionnaire/VariableValue.java
  dialob-api/src/main/java/io/dialob/api/rest/IdAndRevision.java
  dialob-api/src/main/java/io/dialob/api/rest/Items.java
  dialob-api/src/main/java/io/dialob/api/rest/Metadata.java
  dialob-api/src/main/java/io/dialob/api/validation/DialobApiValidatorLocator.java
  dialob-api/src/test/java/io/dialob/api/form/FormTest.java
  dialob-api/src/test/java/io/dialob/api/questionnaire/QuestionnaireTest.java
  dialob-boot/src/main/java/io/dialob/boot/controller/AdminController.java
  dialob-boot/src/test/java/io/dialob/boot/rest/AbstractFormRepositoryTests.java
  dialob-components/dialob-db-sp-spring/src/main/java/io/dialob/db/sp/OnDatabaseTypeCondition.java
  dialob-components/dialob-db-sp-spring/src/test/java/io/dialob/db/sp/OnDatabaseTypeConditionTest.java
  dialob-components/dialob-form-service-rest/src/main/java/io/dialob/form/service/rest/FormsRestService.java
  dialob-components/dialob-form-service-rest/src/main/java/io/dialob/form/service/rest/FormsRestServiceController.java
  dialob-components/dialob-form-service-rest/src/test/java/io/dialob/form/service/rest/FormApiExceptionHandlersTest.java
  dialob-components/dialob-form-service-rest/src/test/java/io/dialob/form/service/rest/FormsRestServiceControllerTest.java
  dialob-components/dialob-form-service/src/main/java/io/dialob/form/service/DialobCsvToFormParser.java
  dialob-components/dialob-form-service/src/main/java/io/dialob/form/service/DialobFormServiceAutoConfiguration.java
  dialob-components/dialob-questionnaire-service-rest/src/main/java/io/dialob/questionnaire/service/rest/QuestionnairesRestService.java
  dialob-components/dialob-questionnaire-service-rest/src/test/java/io/dialob/questionnaire/service/rest/QuestionnairesRestServiceControllerTest.java
  dialob-components/dialob-rule-parser/src/test/java/io/dialob/rule/parser/api/PrimitiveValueTypeTest.java
  dialob-components/dialob-session-engine/src/main/java/io/dialob/session/engine/Utils.java
  dialob-components/dialob-session-engine/src/main/java/io/dialob/session/engine/sp/DialobQuestionnaireSession.java
  dialob-components/dialob-session-engine/src/test/java/io/dialob/session/engine/UtilsTest.java
  dialob-components/dialob-session-engine/src/test/java/io/dialob/session/engine/sp/DialobQuestionnaireSessionBuilderTest.java
  dialob-config-parent/dialob-common/src/main/java/io/dialob/common/Constants.java
  dialob-security-parent/dialob-security-spring/src/main/java/io/dialob/security/spring/apikey/HmacSHA256ApiKeyValidator.java
  dialob-session-boot/src/test/java/io/dialob/session/boot/websocket/QuestionnaireAsyncFunctionExecutorTest.java
Labels: bug, backend
